import type { MenuItem } from "@/lib/types";

/**
 * The Mitea menu.
 *
 * **Seed data — not read at runtime.** The menu lives in Airtable now; this is
 * what the base was populated from, and what `npm run seed:airtable` re-imports.
 * See docs/airtable-catalog.md.
 *
 * **Names and `basePrice` values are transcribed verbatim from the owner's menu
 * document and must not be edited without a new source.** Sections and the
 * items within them are in that document's order too, which is the order they
 * render on /menu. Descriptions are draft copy written for layout —
 * TODO(owner): review and replace.
 *
 * Prices are integer cents.
 *
 * Photography follows the document's own convention: one photo per series,
 * shared by every item in it. Mochi donuts are the exception — that section
 * photographs each box separately. Chizu is the one series the document has no
 * photo for, so those items fall back to the branded placeholder that
 * `image: null` renders.
 */

/** Drink modifier presets, so the group lists below stay readable. */
const TEA = ["size", "sugar", "ice", "toppings"];
const MILK_DRINK = ["size", "sugar", "ice", "milk", "toppings"];
const SMOOTHIE = ["size", "sugar", "toppings"];

export const ITEMS: MenuItem[] = [
  // ── Mochi Donuts ────────────────────────────────────────────────────
  {
    id: "mochi-box-12",
    slug: "mochi-donuts-12-box",
    name: "Mochi Donuts — 12 Box",
    description: "A dozen, your pick of flavours. The one you bring to the office.",
    basePrice: 3400,
    categoryId: "mochi-donuts",
    image: "/images/mochi-donuts-12-box.jpg",
    tags: ["popular"],
    modifierGroupIds: ["donut-flavors-12"],
    squareCatalogObjectId: null,
  },
  {
    id: "mochi-box-6",
    slug: "mochi-donuts-6-box",
    name: "Mochi Donuts — 6 Box",
    description: "Half a dozen, six flavours, no negotiating required.",
    basePrice: 1725,
    categoryId: "mochi-donuts",
    image: "/images/mochi-donuts-6-box.jpg",
    tags: [],
    modifierGroupIds: ["donut-flavors-6"],
    squareCatalogObjectId: null,
  },
  {
    id: "mochi-box-3",
    slug: "mochi-donuts-3-box",
    name: "Mochi Donuts — 3 Box",
    description: "Three to share, or three to not share.",
    basePrice: 925,
    categoryId: "mochi-donuts",
    image: "/images/mochi-donuts-3-box.jpg",
    tags: [],
    modifierGroupIds: ["donut-flavors-3"],
    squareCatalogObjectId: null,
  },
  {
    id: "mochi-single",
    slug: "single-mochi-donut",
    name: "Single Mochi Donut",
    description: "One ring of pull-apart mochi, glazed to order.",
    basePrice: 350,
    categoryId: "mochi-donuts",
    image: "/images/single-mochi-donut.jpg",
    tags: ["popular"],
    modifierGroupIds: ["donut-flavors-1"],
    squareCatalogObjectId: null,
  },

  // ── Brown Sugar Series ──────────────────────────────────────────────
  {
    id: "bs-cookies-cream",
    slug: "brown-sugar-cookies-and-cream",
    name: "Brown Sugar Cookies & Cream",
    description: "Crushed cookies, cream and brown sugar syrup over pearls.",
    basePrice: 630,
    categoryId: "brown-sugar",
    image: "/images/brown-sugar-series.jpg",
    tags: ["popular"],
    modifierGroupIds: MILK_DRINK,
    squareCatalogObjectId: null,
  },
  {
    id: "bs-matcha-latte",
    slug: "brown-sugar-matcha-latte",
    name: "Brown Sugar Matcha Latte",
    description: "Matcha and milk striped with slow-cooked brown sugar.",
    basePrice: 630,
    categoryId: "brown-sugar",
    image: "/images/brown-sugar-series.jpg",
    tags: [],
    modifierGroupIds: MILK_DRINK,
    squareCatalogObjectId: null,
  },
  {
    id: "bs-creme-brulee-milk-tea",
    slug: "brown-sugar-creme-brulee-milk-tea",
    name: "Brown Sugar Crème Brûlée Milk Tea",
    description: "Brown sugar milk tea with a torched crust on top.",
    basePrice: 590,
    categoryId: "brown-sugar",
    image: "/images/brown-sugar-series.jpg",
    tags: [],
    modifierGroupIds: MILK_DRINK,
    squareCatalogObjectId: null,
  },
  {
    id: "bs-milk-tea",
    slug: "brown-sugar-milk-tea",
    name: "Brown Sugar Milk Tea",
    description: "The original — syrup striped down the cup, pearls still warm.",
    basePrice: 550,
    categoryId: "brown-sugar",
    image: "/images/brown-sugar-series.jpg",
    tags: ["popular"],
    modifierGroupIds: MILK_DRINK,
    squareCatalogObjectId: null,
  },
  {
    id: "bs-roasted-oolong-milk-tea",
    slug: "brown-sugar-roasted-oolong-milk-tea",
    name: "Brown Sugar Roasted Oolong Milk Tea",
    description: "Roasted oolong against dark syrup. Toasty rather than sweet.",
    basePrice: 580,
    categoryId: "brown-sugar",
    image: "/images/brown-sugar-series.jpg",
    tags: [],
    modifierGroupIds: MILK_DRINK,
    squareCatalogObjectId: null,
  },

  // ── Energy Series ───────────────────────────────────────────────────
  {
    id: "en-strawberry-infusion",
    slug: "strawberry-infusion",
    name: "Strawberry Infusion",
    description: "Strawberry over ice with an energy base. Built for the 3pm wall.",
    basePrice: 900,
    categoryId: "energy",
    image: "/images/energy-series.jpg",
    tags: ["new"],
    modifierGroupIds: TEA,
    squareCatalogObjectId: null,
  },
  {
    id: "en-blue-raspberry-infusion",
    slug: "blue-raspberry-infusion",
    name: "Blue Raspberry Infusion",
    description: "Blue raspberry, cold and electric.",
    basePrice: 900,
    categoryId: "energy",
    image: "/images/energy-series.jpg",
    tags: ["new"],
    modifierGroupIds: TEA,
    squareCatalogObjectId: null,
  },
  {
    id: "en-pink-pear-lemonade-infusion",
    slug: "pink-pear-lemonade-infusion",
    name: "Pink Pear Lemonade Infusion",
    description: "Pink pear and lemonade with a lift behind it.",
    basePrice: 900,
    categoryId: "energy",
    image: "/images/energy-series.jpg",
    tags: ["new"],
    modifierGroupIds: TEA,
    squareCatalogObjectId: null,
  },

  // ── Fresh Fruit Tea ─────────────────────────────────────────────────
  {
    id: "fft-pink-pear-green",
    slug: "supreme-pink-pear-green-tea",
    name: "Supreme Pink Pear Green Tea",
    description: "Pink pear over green tea. Crisp and barely sweet.",
    basePrice: 650,
    categoryId: "fresh-fruit-tea",
    image: "/images/fresh-fruit-tea.jpg",
    tags: [],
    modifierGroupIds: TEA,
    squareCatalogObjectId: null,
  },
  {
    id: "fft-strawberry-green",
    slug: "supreme-strawberry-green-tea",
    name: "Supreme Strawberry Green Tea",
    description: "Whole strawberries muddled into cold green tea.",
    basePrice: 700,
    categoryId: "fresh-fruit-tea",
    image: "/images/fresh-fruit-tea.jpg",
    tags: ["popular"],
    modifierGroupIds: TEA,
    squareCatalogObjectId: null,
  },
  {
    id: "fft-strawberry-pineapple-green",
    slug: "supreme-strawberry-pineapple-green-tea",
    name: "Supreme Strawberry Pineapple Green Tea",
    description: "Real strawberry and pineapple shaken through green tea.",
    basePrice: 730,
    categoryId: "fresh-fruit-tea",
    image: "/images/fresh-fruit-tea.jpg",
    tags: [],
    modifierGroupIds: TEA,
    squareCatalogObjectId: null,
  },
  {
    id: "fft-pineapple-green",
    slug: "supreme-pineapple-green-tea",
    name: "Supreme Pineapple Green Tea",
    description: "Pineapple and green tea, tart right through.",
    basePrice: 650,
    categoryId: "fresh-fruit-tea",
    image: "/images/fresh-fruit-tea.jpg",
    tags: [],
    modifierGroupIds: TEA,
    squareCatalogObjectId: null,
  },
  {
    id: "fft-peach-green",
    slug: "supreme-peach-green-tea",
    name: "Supreme Peach Green Tea",
    description: "Peach steeped into green tea and served cold.",
    basePrice: 630,
    categoryId: "fresh-fruit-tea",
    image: "/images/fresh-fruit-tea.jpg",
    tags: [],
    modifierGroupIds: TEA,
    squareCatalogObjectId: null,
  },
  {
    id: "fft-peach-passionfruit-green",
    slug: "supreme-peach-passionfruit-green-tea",
    name: "Supreme Peach Passionfruit Green Tea",
    description: "Peach and passionfruit over green tea. Sharp and floral.",
    basePrice: 630,
    categoryId: "fresh-fruit-tea",
    image: "/images/fresh-fruit-tea.jpg",
    tags: [],
    modifierGroupIds: TEA,
    squareCatalogObjectId: null,
  },
  {
    id: "fft-pina-colada",
    slug: "supreme-pina-colada-tea",
    name: "Supreme Piña Colada Tea",
    description: "Pineapple and coconut over tea. No rum, no regrets.",
    basePrice: 650,
    categoryId: "fresh-fruit-tea",
    image: "/images/fresh-fruit-tea.jpg",
    tags: [],
    modifierGroupIds: TEA,
    squareCatalogObjectId: null,
  },

  // ── Milk Tea ────────────────────────────────────────────────────────
  {
    id: "mt-winter-melon",
    slug: "winter-melon-milk-tea",
    name: "Winter Melon Milk Tea",
    description: "Caramel-sweet winter melon with milk. Softer than it sounds.",
    basePrice: 550,
    categoryId: "milk-tea",
    image: "/images/milk-tea.jpg",
    tags: [],
    modifierGroupIds: MILK_DRINK,
    squareCatalogObjectId: null,
  },
  {
    id: "mt-roasted-oolong",
    slug: "roasted-oolong-milk-tea",
    name: "Roasted Oolong Milk Tea",
    description: "Charcoal-roasted oolong, milk, and a long finish.",
    basePrice: 550,
    categoryId: "milk-tea",
    image: "/images/milk-tea.jpg",
    tags: [],
    modifierGroupIds: MILK_DRINK,
    squareCatalogObjectId: null,
  },
  {
    id: "mt-hazelnut",
    slug: "hazelnut-milk-tea",
    name: "Hazelnut Milk Tea",
    description: "Toasted hazelnut over black tea and milk.",
    basePrice: 550,
    categoryId: "milk-tea",
    image: "/images/milk-tea.jpg",
    tags: [],
    modifierGroupIds: MILK_DRINK,
    squareCatalogObjectId: null,
  },
  {
    id: "mt-classic",
    slug: "classic-milk-tea",
    name: "Classic Milk Tea",
    description: "Black tea and milk, balanced the way it should be.",
    basePrice: 550,
    categoryId: "milk-tea",
    image: "/images/milk-tea.jpg",
    tags: ["popular"],
    modifierGroupIds: MILK_DRINK,
    squareCatalogObjectId: null,
  },
  {
    id: "mt-jasmine",
    slug: "jasmine-milk-tea",
    name: "Jasmine Milk Tea",
    description: "Jasmine green tea with milk. Floral and light.",
    basePrice: 550,
    categoryId: "milk-tea",
    image: "/images/milk-tea.jpg",
    tags: [],
    modifierGroupIds: MILK_DRINK,
    squareCatalogObjectId: null,
  },
  {
    id: "mt-coconut",
    slug: "coconut-milk-tea",
    name: "Coconut Milk Tea",
    description: "Coconut and black tea, creamy without being heavy.",
    basePrice: 550,
    categoryId: "milk-tea",
    image: "/images/milk-tea.jpg",
    tags: [],
    modifierGroupIds: MILK_DRINK,
    squareCatalogObjectId: null,
  },
  {
    id: "mt-salted-caramel",
    slug: "salted-caramel-milk-tea",
    name: "Salted Caramel Milk Tea",
    description: "Caramel and sea salt over milk tea. Dessert in a cup.",
    basePrice: 550,
    categoryId: "milk-tea",
    image: "/images/milk-tea.jpg",
    tags: [],
    modifierGroupIds: MILK_DRINK,
    squareCatalogObjectId: null,
  },

  // ── Smoothie Series ─────────────────────────────────────────────────
  {
    id: "sm-mango",
    slug: "mango-smoothie",
    name: "Mango Smoothie",
    description: "Blended mango, thick enough for a spoon.",
    basePrice: 800,
    categoryId: "smoothie",
    image: "/images/smoothie-series.jpg",
    tags: [],
    modifierGroupIds: SMOOTHIE,
    squareCatalogObjectId: null,
  },
  {
    id: "sm-coconut",
    slug: "coconut-smoothie",
    name: "Coconut Smoothie",
    description: "Coconut blended thick and cold.",
    basePrice: 750,
    categoryId: "smoothie",
    image: "/images/smoothie-series.jpg",
    tags: ["vegan"],
    modifierGroupIds: SMOOTHIE,
    squareCatalogObjectId: null,
  },
  {
    id: "sm-strawberry",
    slug: "strawberry-smoothie",
    name: "Strawberry Smoothie",
    description: "Strawberries blended cold. Add mitea and it becomes dessert.",
    basePrice: 800,
    categoryId: "smoothie",
    image: "/images/smoothie-series.jpg",
    tags: [],
    modifierGroupIds: SMOOTHIE,
    squareCatalogObjectId: null,
  },
  {
    id: "sm-banana-strawberry",
    slug: "banana-strawberry-smoothie",
    name: "Banana Strawberry Smoothie",
    description: "Banana and strawberry, the pairing that never misses.",
    basePrice: 800,
    categoryId: "smoothie",
    image: "/images/smoothie-series.jpg",
    tags: [],
    modifierGroupIds: SMOOTHIE,
    squareCatalogObjectId: null,
  },
  {
    id: "sm-banana-blueberry",
    slug: "banana-blueberry-smoothie",
    name: "Banana Blueberry Smoothie",
    description: "Blueberries and banana blended smooth.",
    basePrice: 800,
    categoryId: "smoothie",
    image: "/images/smoothie-series.jpg",
    tags: [],
    modifierGroupIds: SMOOTHIE,
    squareCatalogObjectId: null,
  },

  // ── Tea Series ──────────────────────────────────────────────────────
  {
    id: "ts-pure-honey-jasmine-green",
    slug: "pure-honey-jasmine-green-tea",
    name: "Pure Honey Jasmine Green Tea",
    description: "Jasmine green tea sweetened with honey. Nothing else.",
    basePrice: 530,
    categoryId: "tea",
    image: "/images/tea-series.jpg",
    tags: ["vegan"],
    modifierGroupIds: TEA,
    squareCatalogObjectId: null,
  },
  {
    id: "ts-jasmine-green",
    slug: "jasmine-green-tea",
    name: "Jasmine Green Tea",
    description: "Straight jasmine green, brewed fresh through the day.",
    basePrice: 500,
    categoryId: "tea",
    image: "/images/tea-series.jpg",
    tags: ["vegan"],
    modifierGroupIds: TEA,
    squareCatalogObjectId: null,
  },
  {
    id: "ts-kungfu-black",
    slug: "kungfu-black-tea",
    name: "KungFu Black Tea",
    description: "Deep, malty black tea. The leaf on its own terms.",
    basePrice: 500,
    categoryId: "tea",
    image: "/images/tea-series.jpg",
    tags: ["vegan"],
    modifierGroupIds: TEA,
    squareCatalogObjectId: null,
  },

  // ── Chizu Series ────────────────────────────────────────────────────
  {
    id: "chizu-pink-pear-green",
    slug: "chizu-pink-pear-green-tea",
    name: "Chizu Pink Pear Green Tea",
    description: "Pink pear and green tea, capped with cheese foam.",
    basePrice: 800,
    categoryId: "chizu",
    image: null,
    tags: [],
    modifierGroupIds: TEA,
    squareCatalogObjectId: null,
  },
  {
    id: "chizu-strawberry-green",
    slug: "chizu-strawberry-green-tea",
    name: "Chizu Strawberry Green Tea",
    description: "Strawberry green tea under a salted cheese cap. Sip through the foam.",
    basePrice: 850,
    categoryId: "chizu",
    image: null,
    tags: ["popular"],
    modifierGroupIds: TEA,
    squareCatalogObjectId: null,
  },
  {
    id: "taro-latte",
    slug: "taro-latte",
    name: "Taro Latte",
    description: "Stone-ground taro whisked into milk. Purple, nutty, faintly sweet.",
    basePrice: 740,
    categoryId: "chizu",
    image: null,
    tags: ["popular"],
    modifierGroupIds: MILK_DRINK,
    squareCatalogObjectId: null,
  },
  {
    id: "chizu-pineapple-green",
    slug: "chizu-pineapple-green-tea",
    name: "Chizu Pineapple Green Tea",
    description: "Bright pineapple green tea with a salted cheese cap.",
    basePrice: 680,
    categoryId: "chizu",
    image: null,
    tags: [],
    modifierGroupIds: TEA,
    squareCatalogObjectId: null,
  },
  {
    id: "thai-tea-creme-brulee",
    slug: "thai-tea-creme-brulee",
    name: "Thai Tea Crème Brûlée",
    description: "Spiced Thai tea under a torched sugar crust.",
    basePrice: 660,
    categoryId: "chizu",
    image: null,
    tags: [],
    modifierGroupIds: MILK_DRINK,
    squareCatalogObjectId: null,
  },
  {
    id: "chizu-matcha-latte",
    slug: "chizu-matcha-latte",
    name: "Chizu Matcha Latte",
    description: "Ceremonial-grade matcha, milk, and a salted cheese finish.",
    basePrice: 660,
    categoryId: "chizu",
    image: null,
    tags: [],
    modifierGroupIds: MILK_DRINK,
    squareCatalogObjectId: null,
  },
  {
    id: "chizu-milk-tea",
    slug: "chizu-milk-tea",
    name: "Chizu Milk Tea",
    description: "House milk tea, cheese foam on top. The one to start with.",
    basePrice: 670,
    categoryId: "chizu",
    image: null,
    tags: [],
    modifierGroupIds: MILK_DRINK,
    squareCatalogObjectId: null,
  },
  {
    id: "chizu-kungfu-black",
    slug: "chizu-kungfu-black-tea",
    name: "Chizu KungFu Black Tea",
    description: "Deep-brewed black tea, cheese foam, nothing else needed.",
    basePrice: 570,
    categoryId: "chizu",
    image: null,
    tags: [],
    modifierGroupIds: TEA,
    squareCatalogObjectId: null,
  },
  {
    id: "chizu-strawberry-pineapple-green",
    slug: "chizu-strawberry-pineapple-green-tea",
    name: "Chizu Strawberry Pineapple Green Tea",
    description: "Strawberry and pineapple over green tea, finished with cheese foam.",
    basePrice: 780,
    categoryId: "chizu",
    image: null,
    tags: [],
    modifierGroupIds: TEA,
    squareCatalogObjectId: null,
  },
  {
    id: "chizu-peach-latte",
    slug: "chizu-peach-latte",
    name: "Chizu Peach Latte",
    description: "Peach and milk, cheese foam over the top.",
    basePrice: 640,
    categoryId: "chizu",
    image: null,
    tags: [],
    modifierGroupIds: MILK_DRINK,
    squareCatalogObjectId: null,
  },
];
